# Generated by Django 2.2.7 on 2019-12-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20191127_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=512)),
                ('nickname', models.CharField(max_length=512)),
                ('sex', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('access_token', models.CharField(max_length=512)),
                ('expiredTime', models.CharField(max_length=30)),
            ],
        ),
    ]
