# Generated by Django 2.2.7 on 2019-12-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=30)),
                ('cartId', models.CharField(max_length=30)),
                ('range', models.CharField(max_length=512)),
                ('persent', models.CharField(max_length=512)),
                ('images', models.CharField(max_length=1024)),
            ],
        ),
    ]
